#! /bin/bash

mkdir tmp 2> /dev/null

INSTALLATIONS=(

# Common
kde-plasma-desktop
kde-spectacle
fish

# Compilation
build-essential
gcc
make
cmake

# Coding
qtcreator
codeblocks-contrib

# Etc
pciutils
linux-headers-$(uname -r)

# Network
ufw
nmap

)

if (apt show code &> /dev/null); then
echo "Code installed!"
else
curl https://vscode.download.prss.microsoft.com/dbazure/download/stable/e170252f762678dec6ca2cc69aba1570769a5d39/code_1.88.1-1712771838_amd64.deb --output tmp/code.deb
sudo apt install ./tmp/code.deb
fi

{
sudo apt update && sudo apt upgrade -y &> /dev/null

for installPacket in ${INSTALLATIONS[@]}; do
if (dpkg -l "$installPacket" &> /dev/null); then
echo -e "\033[32mOK\033[0m Package already installed: $installPacket"
else
sudo apt install "$installPacket" -y
fi
done
} 2> errors.log


# Setup libraries
LIBRARIES=(

)

{
for library in ${LIBRARIES[@]}; do
echo "Libs!"
done
} 2>> errors.log


# Other libs
LIBRARIES=(
https://github.com/msgpack/msgpack-c/archive/refs/tags/cpp-6.1.1.zip
)

{
for library in ${LIBRARIES[@]}; do
rm -rf tmp/*
RESULT=$(cd tmp && wget "$library" && unzip *.zip && cd LIB && mkdir BUILD && cd BUILD && cmake .. && sudo make install)
if (RESULT); then
echo -e "\033[32mOK\033[0m Lib installed!"
else
echo -e "\033[31mERR\033[0m Lib NOT installed!"
fi
done
} 2>> errors.log


# Setup github
# ssh-keygen -t ed25519 -C "main.com"
# git config --global user.email="mail.com"
