#! /bin/bash

sudo apt build-dep qtbase5-dev 2>> logfile.txt

sudo apt install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libmd4c* build-essential libgl1-mesa-dev libfontconfig1-dev libfreetype6-dev libx11-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libx11-xcb-dev libxcb-glx0-dev libssl-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libasound2-dev libbz2-dev libgcrypt20-dev libicu-dev libpng-dev libjpeg-dev libsqlite3-dev zlib1g-dev libmysqlclient-dev libpq-dev unixodbc-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev libwebp-dev libopus-dev libavcodec-dev libavformat-dev libswscale-dev libavresample-dev libssl-dev libpulse-dev libglib2.0-dev libudev-dev libopenal-dev libalut-dev libvulkan-dev -y 2>>logfile.txt

sudo apt install libfontconfig1-dev libfreetype6-dev libx11-dev libx11-xcb-dev libxext-dev libxfixes-dev libxi-dev libxrender-dev libxcb1-dev libxcb-cursor-dev libxcb-glx0-dev libxcb-keysyms1-dev libxcb-image0-dev libxcb-shm0-dev libxcb-icccm4-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-shape0-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-util-dev libxcb-xinerama0-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev -y 2>> logfile.txt

echo "Installation done"
