#! /bin/bash

RESULT_DIR="$2/Docs"
mkdir "$RESULT_DIR"

DOCTYPES=(
"doc"
"docx"
"odt"
"ods"
"xls"
"xlsx"
)
DOCTYPES_COUNT=${#DOCTYPES[@]}
COUNTER=1;

for t in ${#DOCTYPES[@]}; do
echo -en "\r\033[K\033[33m[$COUNTER/$DOCTYPES_COUNT]Moving $t..."
((COUNTER++))

mv $(find "$1" -iname *"$t") "$RESULT_DIR" &> "../docMove.log"
done
echo -e "\r\033[K\033[32mComplete\033[0m";
