#! /bin/bash

if [ "$1" == "" ]; then
    echo "Choose name for archive"
    exit 1
else
    if [ "$2" == "" ]; then
        echo "Choose targets to archive"
        exit 1
    fi
fi

7z -t7z a -p -mhe=on -m0=lzma2 -mx=9 -mfb=64 -md=32m -ms=on $1 $@
